import Head from 'next/head'
import styles from '@styles/components/Layout.module.css'
import Navbar from '@components/Navbar'
import Footer from '@components/Footer'
import { ReactElement } from 'react'

type LayoutProps = {
  children: ReactElement | ReactElement[]
}

const Layout = ({ children }: LayoutProps): ReactElement => (
  <>
    <Head>
      <title>HairSalon</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Navbar />
    <div className={styles.bg} />
    <div className={styles.container}>
      <main className={styles.main}>{children}</main>
    </div>
    <Footer />
  </>
)

export default Layout
