import Head from 'next/head'
import Navbar from '@components/Navbar'
import Footer from '@components/Footer'
import { ReactElement } from 'react'

type Props = {
  children: ReactElement | ReactElement[]
}

const MainLayout = ({ children }: Props): ReactElement => (
  <div className="min-h-screen h-full bg-gradient-to-r from-blue-800 via-green-700 to-indigo-600">
    <Head>
      <title>HairSalon</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Navbar />
    <main className="px-12 py-9">{children}</main>
    <Footer />
  </div>
)

export default MainLayout
