import Head from 'next/head'
import InfoBox from '@components/InfoBox'
import styles from '@styles/404.module.css'
import { NextPage } from 'next'

const _404Page: NextPage = () => {
  return (
    <InfoBox>
      <Head>
        <title>HairSalon - 404</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.box}>
        <h1>Oops...</h1>
        <hr />
        <h2> This page could not be found...</h2>
        <h6>STATUS: 404</h6>
      </div>
    </InfoBox>
  )
}

export default _404Page
