import React, { useState } from 'react'
import { NextPage } from 'next'
import Head from 'next/head'
import InfoBox from '@components/InfoBox'
import Layout from '@layouts/default'
import Input from '@components/Input'

const About: NextPage = () => {
  const [query, setQuery] = useState({
    name: '',
    surename: '',
    email: '',
    phone: '',
    date: '',
  })

  const hendleParam = (element: any) => {
    const name = element.target.name
    const value = element.target.value
    setQuery((prevState) => ({
      ...prevState,
      [name]: value,
    }))
  }

  const formSubmit = () => {
    const formData: { [key: string]: any } = {}
    Object.entries(query).forEach(([key, value]) => {
      formData[key] = value
    })
    fetch('./api/visits', {
      method: 'POST',
      body: JSON.stringify(formData),
      headers: {
        'Content-Type': 'application/json',
      },
    }).then(() =>
      setQuery({ name: '', surename: '', email: '', phone: '', date: '' })
    )
    console.log(JSON.stringify(formData))
  }
  return (
    <Layout>
      <InfoBox>
        <Head>
          <title>HairSalon - Book</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <h1>Book Hairdresser</h1>
        <form>
          <Input
            labelValue={'Name: '}
            name="name"
            type="text"
            onChange={hendleParam}
          />
          <br />
          <Input
            labelValue={'Surename: '}
            name="name"
            type="text"
            onChange={hendleParam}
          />
          <br />
          <Input
            labelValue={'Email: '}
            name="name"
            type="text"
            onChange={hendleParam}
          />
          <br />
          <Input
            labelValue={'Phone: '}
            name="name"
            type="text"
            onChange={hendleParam}
          />
          <br />
          <Input
            labelValue={'Date: '}
            name="name"
            type="text"
            onChange={hendleParam}
          />
          <br />
          <button type="button" onClick={formSubmit}>
            Send
          </button>
        </form>
      </InfoBox>
    </Layout>
  )
}

export default About
